name: Enterprise cicd pipeline
on: 
  push:
    branches:
      - qa
    paths:
      - client/**
      - server/**
      - .github/workflows/qa-cicd.yaml
permissions:
  contents: write
  id-token: write
jobs:
  gitleaks-scan:
    name: gitleaks scan
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v6

      - name: run gitleaks scan
        run: |
          docker run --rm \
          -v "${{github.workspace}}:/repo" \
          zricethezav/gitleaks:latest detect \
          --source=/repo \
          --report-format=json \
          --report-path=/repo/gitleaks-report.json \
          --redact \
          --exit-code 0

      - name: Upload gitleaks report
        uses : actions/upload-artifact@v4
        with:
          name: gitleaks-report
          path: gitleaks-report.json
          if-no-files-found: warn
  checkov-terraform:
    name: checkov terraform scan
    runs-on: ubuntu-latest
    needs: gitleaks-scan
    steps:
      - name: checkout source code
        uses: actions/checkout@v4
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: install checkov
        run: pip install checkov
      - name: run checkov terraform scan
        run: |
          checkov -d . \
            --framework terraform \
            -- output json > checkov-terraform-report.json || true
      - name: upload checkov terraform report
        uses: actions/upload-artifact@v4
        with:
          name: checkov-terraform-report
          path: checkov-terraform-report.json
          if-no-files-found: warn
          
  checkov-k8s:
    name: checkov kubernetes scan
    runs-on: ubuntu-latest
    needs: gitleaks-scan
    steps:
      - name: checkout source code
        uses: actions/checkout@v4
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: install checkov
        run: pip install checkov
      - name: run checkov kubernetes scan
        run: |
          checkov -d . \
            --framework kubernetes \
            -- output json > checkov-k8s-report.json || true
      - name: upload checkov kubernetes report
        uses: actions/upload-artifact@v4
        with:
          name: checkov-k8s-report
          path: checkov-k8s-report.json
          if-no-files-found: warn
          
  checkov-dockerfile:
    name: checkov dockerfile scan
    runs-on: ubuntu-latest
    needs: gitleaks-scan
    steps:
      - name: checkout source code
        uses: actions/checkout@v4
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: install checkov
        run: pip install checkov
      - name: run checkov docker scan
        run: |
          checkov -d . \
            --framework dockerfile \
            -- output json > checkov-dockerfile-report.json || true
      - name: upload checkov dockerfile report
        uses: actions/upload-artifact@v4
        with:
          name: checkov-dockerfile-report
          path: checkov-dockerfile-report.json
          if-no-files-found: warn  

  client-trivy-fs:
    name: client trivy fs scan
    runs-on: ubuntu-latest
    needs: gitleaks-scan
    steps:
    - name: checkout source code
      uses: actions/checkout@v4

    - name: install trivy
      uses: aquasecurity/setup-trivy@v0.2.6
      with:
        version: latest
        cache: true

    - name: verify trivy installation
      run: |
        trivy --version
        which trivy

    - name: Run Trivy FS scan on client
      run: |
        trivy fs ./client \
          --format json \
          --output client-trivy-fs-report.json \
          --severity HIGH,CRITICAL \
          --ignore-unfixed \
          --exit-code 0

    - name: Run Trivy FS scan on client (TABLE)
      run: |
        trivy fs ./client \
          --format table \
          --severity HIGH,CRITICAL \
          --ignore-unfixed \
          --exit-code 0 > client-trivy-fs-report.txt

    - name: Upload client trivy json report
      uses: actions/upload-artifact@v4
      with:
        name: client-trivy-fs-json-report
        path: client-trivy-fs-report.json
        if-no-files-found: warn

    - name: upload client truvy table report
      uses: actions/upload-artifact@v4
      with:
        name: client-trivy-fs-report
        path: client-trivy-fs-report.txt
        if-no-files-found: warn
        
  server-trivy-fs:
    name: server trivy fs scan
    runs-on: ubuntu-latest
    needs: gitleaks-scan
    steps:
    - name: checkout source code
      uses: actions/checkout@v4

    - name: install trivy
      uses: aquasecurity/setup-trivy@v0.2.6
      with:
        version: latest
        cache: true

    - name: verify trivy installation
      run: |
        trivy --version
        which trivy

    - name: Run Trivy FS scan on server
      run: |
        trivy fs ./server \
          --format json \
          --output server-trivy-fs-report.json \
          --severity HIGH,CRITICAL \
          --ignore-unfixed \
          --exit-code 0

    - name: Run Trivy FS scan on server (TABLE)
      run: |
        trivy fs ./server \
          --format table \
          --severity HIGH,CRITICAL \
          --ignore-unfixed \
          --exit-code 0 > server-trivy-fs-report.txt

    - name: Upload server trivy json report
      uses: actions/upload-artifact@v4
      with:
        name: server-trivy-fs-json-report
        path: server-trivy-fs-report.json
        if-no-files-found: warn

    - name: upload server trivy table report
      uses: actions/upload-artifact@v4
      with:
        name: server-trivy-fs-report
        path: server-trivy-fs-report.txt
        if-no-files-found: warn

  client-lint:
    name: Client Lint
    runs-on: ubuntu-latest
    needs:
      - client-trivy-fs
      - checkov-dockerfile
      - checkov-k8s
      - checkov-terraform

    defaults:
      run:
        working-directory: client

    steps:
      - name: checkout source code
        uses: actions/checkout@v4

      - name: setup node js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: client/package.json

      - name: install client dependencies
        run: npm ci

      - name: Run client lint
        run: npm run lint --if-present
        continue-on-error: true
        
  server-lint:
    name: Server Lint
    runs-on: ubuntu-latest
    needs:
      - server-trivy-fs
      - checkov-dockerfile
      - checkov-k8s
      - checkov-terraform

    defaults:
      run:
        working-directory: server

    steps:
      - name: checkout source code
        uses: actions/checkout@v4

      - name: setup node js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: server/package.json

      - name: install server dependencies
        run: npm ci

      - name: Run server lint
        run: npm run lint --if-present
        continue-on-error: true

  client-test:
    name: Client Test
    runs-on: ubuntu-latest
    needs: client-lint

    defaults:
      run:
        working-directory: client

    steps:
      - name: checkout source code
        uses: actions/checkout@v4

      - name: setup nodejs 
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: client/package.json

      - name: Install client dependencies
        run: npm ci

      - name: Run client tests
        run: npm test --if-present
        continue-on-error: true

  server-test:
    name: Server Test
    runs-on: ubuntu-latest
    needs: server-lint

    defaults:
      run:
        working-directory: server

    steps:
      - name: checkout source code
        uses: actions/checkout@v4

      - name: setup nodejs 
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: server/package.json

      - name: Install server dependencies
        run: npm ci

      - name: Run server tests
        run: npm test --if-present
        continue-on-error: true

  sonarqube:
    name: sonarqube analysis
    runs-on: ubuntu-latest
    needs: 
        - server-test
        - client-test
    steps:
      - uses: actions/checkout@v4
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting.
          # 1 means only latest commit will be downloaded, 0 means complete git history
          fetch-depth: 0

      # Triggering SonarQube analysis as results of it are required by Quality Gate check.
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      # Check the Quality Gate status.
      - name: SonarQube Quality Gate check
        id: sonarqube-quality-gate-check
        uses: sonarsource/sonarqube-quality-gate-action@master
        with:
          pollingTimeoutSec: 600
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }} #OPTIONAL

      # Optionally you can use the output from the Quality Gate in another step.
      # The possible outputs of the `quality-gate-status` variable are `PASSED`, `WARN` or `FAILED`.
      - name: "Example show SonarQube Quality Gate Status value"
        run: echo "The Quality Gate status is ${{ steps.sonarqube-quality-gate-check.outputs.quality-gate-status }}"
        
  client-build:
    name: client Build
    runs-on: ubuntu-latest
    needs: client-test
    defaults:
      run:
        working-directory: client
    steps:
      - name: checkout source code
        uses: actions/checkout@v4

      - name: setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: client/package-lock.json

      - name: install client dependencies
        run: npm ci

      - name: build client
        run: npm run build --if-present
        
        
  docker:
    name: build docker image and push
    runs-on: ubuntu-latest
    needs: 
      - client-build
      - sonarqube
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: set up QEMU
        uses: docker/setup-qemu-action@v4

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v4

      - name: build and push
        uses: docker/build-push-action@v7
        with:
          load: true
          push: false
          tags: |
            amalvaasish/test-repo:${{ github.sha }}
            amalvaasish/test-repo:latest
            
      - name: install trivy
        uses: aquasecurity/setup-trivy@v0.2.6
        with:
          version: latest
          cache: true
  
      - name: verify trivy installation
        run: |
          trivy --version
          which trivy
  
      - name: Run Trivy image scan
        run: |
          trivy image amalvaasish/test-repo:${{ github.sha }} \
            --format json \
            --output image-trivy-report.json \
            --severity HIGH,CRITICAL \
            --ignore-unfixed \
            --exit-code 0
  
      - name: Run Trivy image scan (TABLE)
        run: |
          trivy image amalvaasish/test-repo:${{ github.sha }} \
            --format table \
            --severity HIGH,CRITICAL \
            --ignore-unfixed \
            --exit-code 0 > image-trivy-report.txt
  
      - name: Upload image trivy json report
        uses: actions/upload-artifact@v4
        with:
          name: image-trivy-json-report
          path: image-trivy-report.json
          if-no-files-found: warn

      - name: upload image trivy table report
        uses: actions/upload-artifact@v4
        with:
          name: image-trivy-report
          path: image-trivy-report.txt
          if-no-files-found: warn

      - name: Generate source SBOM
        uses: anchore/sbom-action@v0
        with:
          path: .
          format: spdx-json
          output-file: source-sbom.spdx.json
          upload-artifact: true

      - name: Generate image SBOM
        uses: anchore/sbom-action@v0
        with:
          image: amalvaasish/test-repo:${{ github.sha }}
          format: spdx-json
          output-file: image-sbom.spdx.json
          upload-artifact: true

      - name: Push
        uses: docker/build-push-action@v7
        with:
          push: true
          tags: |
            amalvaasish/test-repo:${{ github.sha }}
            amalvaasish/test-repo:latest
  update-qa-manifest:
    name: Update QA Manifest
    runs-on: ubuntu-latest
    needs: docker
    permissions: 
      contents: write
    steps:
      - name: checkout qa branch
        uses: actions/checkout@v4
      - name: Update image tag in manifest
        run: |
          sed -i "s|image: amalvaasish/test-repo:.*|image: amalvaasish/test-repo:${GITHUB_SHA}|g" k8-manifests/qa/app-deployment.yaml
      - name: show updated manifest (debug)
        run: |
          cat k8-manifests/qa/app-deployment.yaml
      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add k8-manifests/qa/app-deployment.yaml
          git commit -m "update qa image to ${GITHUB_SHA}[skip ci]" || echo "No changes to commit"
          git push origin qa

  deploy-to-k8s:
    name: Deploy to kubernetes QA
    runs-on: ubuntu-latest
    needs: update-qa-manifest
    env:
      AWS_REGION: ap-south-1
      EKS_CLUSTER_NAME: my-cluster
      K8S_NAMESPACE: qa
    steps:
      - name: checkout source code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: qa
      - name: Configure aws credentials from github oidc
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}
      - name: setup kubectl
        uses: azure/setup-kubectl@v4
      - name: generate kubeconfig for EKS
        run: aws eks update-kubeconfig --region "${AWS_REGION}" --name "${EKS_CLUSTER_NAME}"
      - name: verify identity
        run: |
          aws sts get-caller-identity
          kubectl config current-context

      - name: verify namespace
        run: |
          kubectl get pods -n "${K8S_NAMESPACE}"
          kubectl get services -n "${K8S_NAMESPACE}"
          kubectl auth can-i create deployments -n "${K8S_NAMESPACE}"
          kubectl auth can-i create services -n "${K8S_NAMESPACE}"
          kubectl auth can-i create ingresses.networking.k8s.io -n "${K8S_NAMESPACE}"

      - name: Deploy manifests
        run: |
          kubectl apply -f k8s-manifests/qa/ -n "${K8S_NAMESPACE}"
      - name: Verify rollout
        run: |
          kubectl rollout status deployment/nodejs-app -n "${K8S_NAMESPACE}" --timeout=180s 
          
    
  
         
     
